### ISSUE TITLE
Foldable nav behavior changes as of Hugo 0.100.0

### ISSUE THREAD

**Issue by chalin** [google/docsy#1065]
Visit a section with children and prior to Hugo 0.100.0 and you'll see the section entry open (with children visible) in the left nav. After 0.100.0, the same left-nav entry isn't open. For example, compare the state of the left-nav for the following two preview builds:

- https://deploy-preview-1476--opentelemetry.netlify.app/docs/instrumentation/js/api/ - uses Hugo 0.98
- ~https://deploy-preview-1477--opentelemetry.netlify.app/docs/instrumentation/js/api/ - uses Hugo 0.100.2~ I've updated the PR so the problem no longer appears. I've included below a screenshot illustrating the original problem.

In particular, I'm _guessing_ that we're being hit by the following:

- https://github.com/gohugoio/hugo/issues/9925
- https://github.com/gohugoio/hugo/pull/9926

The resources above suggests a means of preserving the old behavior (which we may or may not want to do). 

Related:

- [0.100.0 release notes](https://github.com/gohugoio/hugo/releases/tag/v0.100.0).

### Screenshots

Hugo 0.98

> <img width="1063" alt="image" src="https://user-images.githubusercontent.com/4140793/175396270-ee3e3147-ff04-4b60-8621-fbadb7bf85b7.png">

Hugo 0.100.2

> <img width="1032" alt="image" src="https://user-images.githubusercontent.com/4140793/175396344-4d81ce20-0822-4301-be97-28c549d46106.png">

**Comment by raum51** [comment]
I had only time for a short look at this issue:

- The problem is the not set CSS class "active-path" for die li tags along the current page path.
- I think we have to redesign line 45 in the sidebar-tree.html partial: https://github.com/google/docsy/blob/9f55cf34808d720bcfff9398c9f9bb7fd8fce4ec/layouts/partials/sidebar-tree.html#L45

Also possible side effects to the JS it the cached sidebar tree version should get checkt: https://github.com/google/docsy/blob/9f55cf34808d720bcfff9398c9f9bb7fd8fce4ec/layouts/partials/sidebar.html#L7-L19
--> After a quick check, I think, the cached version should work fine.

I'm afraid, that I won't find the time to fix it and test it in the 1-2 weeks. So If anybody else can find time, it would be fine. If not, I have a time slot at the beginning of July, where I will update our own Docsy site.

**Comment by chalin** [comment]
@raum51 - Right. No worries, I have a fix, which I'll port this week (and you'll be welcome to comment on if you have the time).
