### ISSUE TITLE
Errors on Initial Setup

### ISSUE THREAD

**Issue by chris-short** [google/docsy#115]
After following the install instructions to use docsy as a standalone theme: https://www.docsy.dev/docs/getting-started/

I receive the following errors when running `hugo server` the first time.

`WARN 2019/07/22 06:37:56 found no layout file for "HTML" for "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.`
`ERROR 2019/07/22 06:38:12 render of "taxonomyTerm" failed: "/Users/cshort/repo/myproject/themes/docsy/layouts/_default/list.rss.xml:19:13": execute of template failed: template: _default/list.rss.xml:19:13: executing "_default/list.rss.xml" at <$.Parent.IsHome>: error calling IsHome: runtime error: invalid memory address or nil pointer dereference`
`ERROR 2019/07/22 06:38:12 failed to render pages: render of "taxonomyTerm" failed: "/Users/cshort/repo/myproject/themes/docsy/layouts/_default/list.rss.xml:19:13": execute of template failed: template: _default/list.rss.xml:19:13: executing "_default/list.rss.xml" at <$.Parent.IsHome>: error calling IsHome: runtime error: invalid memory address or nil pointer dereference`

**Comment by LisaFC** [comment]
Hmm, it's hard to tell without seeing your site files but it looks like you have a file in your site that doesn't match any of the template layouts/you don't have a Hugo home page. (here's how you usually do a home page in Hugo: https://gohugo.io/templates/homepage/)

@sarahmaddox used Docsy as a theme in her own site rather than cloning our example site, so may have some ideas, otherwise I'll take a proper look when I get back from vacation.

**Comment by chris-short** [comment]
Sorry, that was a lackluster bug report.

I created a new hugo project, add and updated docsy as a submodule, then
hugo server. The dependencies appear to be met. This is the typical process
I've followed building a few sites so I don't think the process is wrong.
Let me know if there's more info I can provide that would help.

Chris Short
He/Him/They
Web <https://chrisshort.net/> | Newsletter <https://devopsish.com/> |
Twitter <https://twitter.com/ChrisShort> | LinkedIn
<https://linkedin.com/in/thechrisshort>

**Comment by LisaFC** [comment]
Thanks for the extra info! If @sarahmaddox or @RichieEscarez  can't help I'll take a proper look next time I'm properly online (am currently on holiday...)

**Comment by RichieEscarez** [comment]
Without seeing your code/site its hard to tell what the source of the problem is but after some searching against the error, I found a thread that suggests that you might need to use `disableKinds` (add it to your site's config.toml) if you are not using `taxonomyTerm` (to prevent Hugo from looking for the corresponding layout).

For example:
https://github.com/google/docsy/search?q=taxonomyTerm&unscoped_q=taxonomyTerm

**Comment by LisaFC** [comment]
Chris, did you get this sorted with Richie's suggestion? Otherwise I'll play around with a new project and see if I can reproduce your problem.

**Comment by chris-short** [comment]
Ran through a clean install just now and everything appears to work out of the box. Thank you!
