### ISSUE TITLE
Add link icons to headers for easy link-grabbing

### ISSUE THREAD

**Issue by sarahmaddox** [google/docsy#118]
A contributor to the [Kubeflow docs](https://www.kubeflow.org/docs/about/kubeflow/) - @Bobgy - has recently added auto-generated link icons on every heading. This makes it easy for people to grab the link to a particular section of a doc. (People can grab the same link from the TOC on the right of the page, but many people don't notice the TOC.)

Here's the PR that adds the link icons:
https://github.com/kubeflow/website/pull/1009

**Inviting @Bobgy to contribute this feature to Docsy.**

**Comment by Bobgy** [comment]
Thanks for creating the issue here. I'm happy to contribute here too.

For user requirement, do you think any website that uses docsy will want to turn off this feature?

For implementation,
I briefly viewed folder structure here. I think I should put my script in `assets/js/anchor.js`, then reference it in `layouts/partials/scripts.html`. Do you think that's a good idea? Or maybe right inside `assets/js/base.js`?

**Comment by LisaFC** [comment]
1)I can't imagine anyone *not* wanting link anchors, they're unobtrusive and very useful, so as long as this change doesn't break existing sites I think I'm happy to not have an opt-out for now (if someone requests it we can always put it in)

2)anchor.js works for me!

Thanks for doing this!

**Comment by Bobgy** [comment]
Sounds good! I'll work on this soon.
