### ISSUE TITLE
Cookie info banner is not displaying as intended when using Hugo with Docsy theme

### ISSUE THREAD

**Issue by Aravinda93** [google/docsy#1223]
I am developing a sample website using [Hugo][1] static website generator by using the [Docsy][2] theme. 

The website includes the `Cookie Banner` so I have added the same to my static website by referencing the approach mentioned from here: https://hugocodex.org/add-ons/cookie-consent/.

Ideally, I would like the banner to be visible something like this:

[![enter image description here][3]][3]

But currently its looking something like this:
[![enter image description here][4]][4]

When I have added it along with styles and `partials` its not looking like that. Maybe some style is messing up the child `cookie consent` styles but unable to figure out the same. Can someone please let me know what am I doing wrong here?

I have added my complete code in following github project:
https://github.com/Aravinda93/hugo-docsy-learn

I am quite new to Hugo and Docy so getting bit confused on the folder and file structure hence unable to figure out which parent style is messing up my `Cookie consent` modal. Can someone please help me with some suggestions?

  [1]: https://github.com/gohugoio/hugo
  [2]: https://github.com/google/docsy
  [3]: https://i.stack.imgur.com/1gslp.png
  [4]: https://i.stack.imgur.com/cgXst.png

**Comment by LisaFC** [comment]
Hi there - it's a little hard to tell what styles are being applied without being able to see the page, can you use something like Chrome developer tools to see which styles are being applied to the element?

In general for adding your own CSS styles we recommend adding them in a special _styles_project.scss file in your project's own assets/scss/.. directory rather than editing files under /themes/docsy/ directly:
https://www.docsy.dev/docs/adding-content/lookandfeel/#project-style-files

...that will get pulled in automatically when the CSS is built (it's imported last so it can override existing styles):
https://github.com/google/docsy/blob/main/assets/scss/main.scss#L69

**Comment by Aravinda93** [comment]
@LisaFC Thanks a lot for the response and the guidance.

I tried the approach of creating my own SCSS and Layouts for Cookie page but still for some reason its not displaying as expected. 

I tried to look into the styles using the Chrome -> Developer console but unable to figure out which style is overriding the provided style as there are quite a few styles coming from the Docsy environment.

I have updated my code in:https://github.com/Aravinda93/hugo-docsy-learn
If you get a chance can you please once have a look and suggest something?



<img width="229" alt="Screenshot 2022-09-05 at 17 10 06" src="https://user-images.githubusercontent.com/29374160/188479000-22a52a45-0e15-49c3-b7d5-8f0382163846.png">

**Comment by Aravinda93** [comment]
I was able to make it work using the following solution: [Hugo Community](https://discourse.gohugo.io/t/cookie-banner-is-not-displaying-as-intended-when-using-hugo-with-docsy-theme/40332/9?u=arvind)
