### ISSUE TITLE
How to remove that semi transparent layer above blocks/cover and make the image sharp and clean?

### ISSUE THREAD

**Issue by Nino-Bock** [google/docsy#1230]
In the landing page, specifically the `blocks/cover` block, there is an image in the background.
That image is behind some semi transparent layer which makes the colors less vibrant.

Is there a way to remove that layer and display the image like it is in its original form?

Sure, that blurry and less vibrant colors are a design choice to drive attention to the actual content.
However I'd like to play around with some non modified images, too.

Thanks

**Comment by Nino-Bock** [comment]
I have attached an image.
The left side is part of the website, the right side is the original image.
It's both the same image, but the right one has much more vibrant colors than the left one.

Once in the inspector I have found an element which had `zinden =1`. When setting it to `0` it also transitioned behind that white layer. Unfortunately I can not find that element any more.


![Hugo background](https://user-images.githubusercontent.com/59871695/189719023-c6b9e5cc-da44-410b-808b-5b44062a1d08.png)

**Comment by LisaFC** [comment]
I'll have a look.

**Comment by LisaFC** [comment]
So I've had a further dig around, and I've found it!(I didn't spot it at first because I didn't write this file and it doesn't just affect the image) - there's a dark overlay styling the background block by default to help ensure text visibility:
https://github.com/google/docsy/blob/main/layouts/shortcodes/blocks/cover.html#L27

Look for `td-overlay--dark` in the styles for the section.

The overlay shouldn't make it blurry, though, the only thing I can think of is that Hugo's image processing and/or resizing is affecting the image quality at certain sizes.

See this discussion: https://github.com/google/docsy/discussions/1109

**Comment by Nino-Bock** [comment]
Oh, nice. Thanks.
Blurry was maybe not the right expression for it.
It just makes the colors less vibrant it seems.

Thanks for finding it.

**Comment by LisaFC** [comment]
Happy to help! Ok to close this?

**Comment by Nino-Bock** [comment]
Can I remove the `td-overlay--dark` class via `_project-styles.css`, or do I need to edit `cover.html` directly?

**Comment by LisaFC** [comment]
Yes, you can override it in your site CSS - this is the style you need to override, not sure if you need to take the background colour out (it's a very translucent grey) or just make it completely translucent. You may also need to make it `important!`.

```
.td-overlay--dark::after {
    background-color: rgba(64,63,76,.3);
}
```

**Comment by privatemaker** [comment]
@LisaFC perhaps this should be documented on [Look & Feel](https://www.docsy.dev/docs/adding-content/lookandfeel/) page of the docs? I find this kind of styling common when customizing themes.
