### ISSUE TITLE
Top navbar changes appearence in wide and narrow view. How can I control that behavior?

### ISSUE THREAD

**Issue by Nino-Bock** [google/docsy#1231]
I observed how the navbar background is not consistent in the landing and about-page when the width of the browser windows shrinks.

Once the logo starts to move above the menu entries, the navbar background changes to the color specified for it.
So as soon as the navbar becomes two lines, it sets itself apart from the background image and is above `td-cover-block-0`.

My question is, how can I set the navbar to set itself apart in wide view and how to make it appear above the background image in narrow view?

Thank

**Comment by Nino-Bock** [comment]
I have found out, that setting '.td-navbar-cover' to some color instead of 'transparent' it makes it not transparent in wide view mode.

Is that the correct way to do it?

**Comment by LisaFC** [comment]
Yes, the narrowest version of the site (for mobile/small devices) has a slightly different navbar layout because otherwise all the text generally doesn't fit in it. The background isn't translucent because, if I remember correctly, it doesn't look great/is hard to read on a small screen with a transparent header. We have considered adding an alternative option where the entire menu for mobile is a dropdown as in Docsy site [kubeflow.org]() - thanks for the reminder! See #1058 for details.

The simplest way to disable navbar transparency for all widths is to use a config parameter as described here:
https://www.docsy.dev/docs/adding-content/lookandfeel/#navbar

**Comment by Nino-Bock** [comment]
Thanks a lot for the answer
