### ISSUE TITLE
Docsy + Algolia v3

### ISSUE THREAD

**Issue by jmichelgarcia** [google/docsy#1250]
## Info
Source code: https://github.com/jmichelgarcia/docsy-algolia
Url: https://sensational-chebakia-db2125.netlify.app/

## Details
When using Algolia, the search result displays as a popup, as opposed to what is mentioned in the docs. Is this the expected behavior?

> When you’ve completed these steps, Algolia search should be enabled on your site. **Search results are displayed as a drop-down under the search box**, so you don’t need to add any search results page.

<img width="1478" alt="Screenshot 2022-09-30 at 15 23 52" src="https://user-images.githubusercontent.com/2745523/193291303-e4e09df5-0211-4111-b870-d4567e9938cf.png">

Secondly, once we have a narrow design, there is no search available. Is this expected?

![Screenshot 2022-09-30 at 15 25 14](https://user-images.githubusercontent.com/2745523/193291590-354fc983-324c-4fa7-8b26-a5035b3a988f.png)

**Comment by LisaFC** [comment]
1. Yes, the new Algolia default search results box is a pop-up rather than a drop-down, we should update the docs. I'm not even sure if you *can* easily configure it as a drop-down but I'll look into it.
2. Let me take a look at that, I believe we didn't support sidebar/narrow site search for Algolia because it was a drop-down and didn't really work with the navbar, but if it's a pop-up we *should* be able to support it for sidebar search as well. It may look a bit strange on mobile though. I will experiment!

**Comment by LisaFC** [comment]
1. Proposed update in #1270 
2. It should be possible to get it working for mobile/smaller screens - I've tried and it's easy to put extra searchboxes on a page so the left nav searchbox would work for Algolia. One snag is that the Algolia code requires each searchbox div to have its own id - at the moment we reuse the searchbox code exactly between the two locations so that won't work without a bit of tweaking, you just end up with two divs with the same id and only get the search box for one of them. The other interesting thing is that the new Algolia styling has a "mobile-width" version that's just a magnifying glass (see image) so we could possibly do some nice styling with it.

![image](https://user-images.githubusercontent.com/10744406/194881631-ba17084b-c535-445e-ae3e-f97c6eaa169c.png)

We do still need possibly to look at the sort of mid-width, as it looks our top nav search box disappears before the "mobile" display with the side search above the main text kicks in (and also the Algolia "mobile-width" icon/box). At the very least we need to provide guidance in the docs that you currently need a sidebar search active for mobile/small screen views. Any suggestions welcome!

**Comment by chalin** [comment]
Having investigated a possible solution, @LisaFC will be working on a fix for use of Algolia in the side-nav search. Thanks @LisaFC!

**Comment by jmichelgarcia** [comment]
I'm closing this since fixes are being handled in #1270. Thank you folks!
