### ISSUE TITLE
General questions about using a docsy repo

### ISSUE THREAD

**Issue by aborruso** [google/docsy#131]
Hi,
I'm starting to use Docsy, it seems great. Thank you.

## The submodules

I have installed it using the [Option 1](https://www.docsy.dev/docs/getting-started/#option-1-clone-the-docsy-example-site), and now in my repo I have 4 git sources:

![image](https://user-images.githubusercontent.com/30607/65356783-9b456e80-dbf5-11e9-89c7-b1d5bb957b4d.png)

I think that the way I must work is to not touch `DOCSY`, `FONT-AWESOME` and `BOOTSTRAP`  repos. But only installing Docsy and using it, have changes in  `DOCSY` and  `BOOTSTRAP` repos.
Is it normal? How do I must manage them?

![image](https://user-images.githubusercontent.com/30607/65356929-f24b4380-dbf5-11e9-9c84-dbf16f7320c6.png)

## Translation

I would like to use it for an Italian site. Then I should create `it.toml` file. But where do I have to save it? I think not in `themes/docsy/i18n`, because it's a submodule.

Do I must create a `i18n` in the root and add there the `it.toml` file?

Thank you

**Comment by LisaFC** [comment]
Thanks for your questions!

1)Yes, if you copy our example repo, you'll have three nested submodules - Docsy as a submodule, then Bootstrap and FontAwesome as submodules of Docsy (each submodule is like a shortcut to the repo whose files you want to use at a specific revision). If you make a local clone and recurse into the submodules as we suggest (`--recurse-submodules --depth 1`), you'll get local copies of all those files so that you can build your site on your own computer, but you don't need to do anything with them or commit them to your own repo.

2)Add your it.toml for your translated UI bits to the actual Docsy repo and then update your project with the latest version as described in https://www.docsy.dev/docs/updating/#update-a-docsy-submodule

Hope that helped! Submodules can be a bit confusing....

**Comment by aborruso** [comment]
Thank you
