### ISSUE TITLE
Doc Versioning

### ISSUE THREAD

**Issue by prdsoftware** [google/docsy#1575]
This page: https://www.docsy.dev/docs/adding-content/versioning/

I am trying to implement versioning for my site, and trying to follow the page above.

It mentioned updating hugo.toml, hugo.yaml and hugo.json.  I think these should be config.toml?

In my confil.toml  file, I had to move the "url_latest_version = " variable to an earlier position in the .toml file before the partial would render correctly.  

Also, might be nice to reference where the partial is (main/layouts/partials) so that people can update it if they like.

Finally, some guidance on best practice on version might be helpful also.  eg.  Do you need to upload an entire new version of the site?  Version control etc.  

Thanks!
Rod

**Comment by deining** [comment]
> This page: https://www.docsy.dev/docs/adding-content/versioning/
> It mentioned updating hugo.toml, hugo.yaml and hugo.json. I think these should be config.toml?

No. From the official [hugo docs](https://gohugo.io/getting-started/configuration/#hugotoml-vs-configtoml):

```
In Hugo 0.110.0 we changed the default config base filename to hugo, e.g. hugo.toml.
We will still look for config.toml etc., but we recommend you eventually rename it.
```

**Comment by at055612** [comment]
>Finally, some guidance on best practice on version might be helpful also. eg. Do you need to upload an entire new version of the site? Version control etc.

This may not be best practice or may not suit your situation, but it may be useful. We use docsy to document a product where different people are using different versions of the product.  We version the docs at the product's minor version level, i.e. 1.0, 1.1, 1.3, etc. and each minor version of the docs is a living thing.  Each docs version is a branch in git with the appropriate changes made to its toml file to set its version, the content of the version dropdown, etc.  Changes from older branches get merged up the chain i.e. 1.0 => 1.1 => 1.2 => 1.3 => master.

The branching means if you want to add/change content relating to an old (but still present) feature you do it on the old branch and merge the change up to include it in the newer versions too.  Changes to a brand new product feature get made on the latest version branch.  Changes to the overall look/feel of the site (e.g. upgrading docsy) would get made on the oldest branch and merged up so all versions look consistent.  Judging what change is made where is not always easy though.

Our site it published on gh-pages, triggered by a nightly build on master (so the build scripts only need to be maintained on master).  GitHub actions checks out each version branch in turn and builds the site for that version into a dir.  It has optimisations to check if the branch has changes since last build to save re-building.  All the dirs are then rsync'd to the checked out gh-pages branch and pushed.  The gh-pages then has dirs like:
```
./1.0
./1.1
./1.2
etc.
```
The latest version site is also copied to the root level so any user hitting that always gets the latest, but a user hitting `/1.2` will always get 1.2.

I'm sure there are many ways to manage versioning but this seems to work ok for our requirements.

**Comment by prdsoftware** [comment]
Thanks for the reply = great info which confirms what I was thinking about this topic.  Seems you need to essentially duplicate the entire doc website for each version and then use branching/merging as required to manage topics.

Initially I was hoping for a per-page versioning system rather than an entire duplication of the website, but it is what it is and I can work with it.

Thanks again.

**Comment by emckean** [comment]
Closing as it seems this is resolved, please feel free to reopen.
