### ISSUE TITLE
Adding an image via shortcode 

### ISSUE THREAD

**Issue by sfxworks** [google/docsy#167]
![image](https://user-images.githubusercontent.com/5921035/71553876-98bc9700-29e4-11ea-98a7-f64ca751dfd2.png)

With a clone of the docsy example repo, I tried to add an image via shortcode. Currently running `hugo server -D`

Here is the head:
```
resources:
- src: "**spruce*.png"
  params:
    byline: "Photo: Bjørn Erik Pedersen / CC-BY-SA"
```

And the content:
```
{{< imgproc spruce Fill "786x484" >}}
Norway Spruce Picea abies shoot with foliage buds.
{{< /imgproc >}}
```

I tried naming the image the same thing and everything. I get this error:
```
ERROR 2019/12/29 02:37:30 "C:\Users\shaba\Documents\git\docsy-example\content\en\docs\Getting started\creating-a-network.md:32:1": failed to render shortcode "imgproc": failed to process shortcode: "C:\Users\shaba\Documents\git\docsy-example\themes\docsy\layouts\shortcodes\imgproc.html:9:34": execute of template failed: template: shortcodes/imgproc.html:9:34: executing "shortcodes/imgproc.html" at <$original.Fill>: nil pointer evaluating resource.Resource.Fill
```

**Comment by LisaFC** [comment]
Huh, weird, let me take a look.

**Comment by LisaFC** [comment]
It looks like it can't find the image file. Can you check if the image you want is in the same page bundle as your page, ie it's set up like the Shortcodes page in the user guide with the page itself as an index.md and the image file in the same folder? https://github.com/google/docsy/tree/master/userguide/content/en/docs/Adding%20content/Shortcodes

**Comment by LisaFC** [comment]
Ok, I think I see the problem, it's basically because the imgproc shortcode relies on your page and its resources being bundled together as a Page Bundle, where the page that's using the resources is the index file in the directory. So in your example screenshot it looks like your Getting Started section contains an _index.md file (fine) and an image (fine) and then another standalone Markdown page that's trying to use the image file as a resource too (not fine). If you want to fix what you have there, create a new Creating-a-network **directory** inside Getting Started, make your creating a network page its index.md (no underscore) and put your image file in the same directory.

(if you don't want to use page bundles you can always just do a regular image include and put your images somewhere in your static/ directory)

**Comment by LisaFC** [comment]
Let me know if that works and I can close the issue.

**Comment by sfxworks** [comment]
Hi sorry for the delay
Thanks for looking into this!

I am trying to follow a format for sub-topics similar to what is provided as an example here where it doesn't create a new folder and instead creates new markdown files. https://github.com/google/docsy-example/tree/master/content/en/docs/Tasks 
It's mainly a preference, but can the issue of using the imgproc shortcode be fixed for situations like these later down the road? The work arounds you provided with the regular html method worked fine.

**Comment by LisaFC** [comment]
Unfortunately I think the main limitation there is Hugo's page bundles mechanism which is how the imgproc shortcode finds the image file. I can investigate a bit more though!

In the meantime my experience it's not *much* more work having a bundle folder rather than a standalone page as one of your subsection pages (if you look at https://github.com/google/docsy/tree/master/userguide/content/en/docs/Adding%20content, they're all subtopics, just "Shortcodes" is a page bundle rather than a standalone Markdown file)

**Comment by LisaFC** [comment]
Yes, from looking up more about page resources they pretty much don't work unless the page is a page bundle index or _index.

Another shortcode you could try instead is the Hugo built-in Figure, which doesn't rely on the image being a page resource: https://gohugo.io/content-management/shortcodes/#figure
