### ISSUE TITLE
Docsy does not respect configuration parameter "disableHugoGeneratorInject"

### ISSUE THREAD

**Issue by nettozahler** [google/docsy#1707]
According to https://gohugo.io/getting-started/configuration/ the behavior should be like this:

Hugo will, by default, inject a generator meta tag in the HTML head on the home page only. You can turn it off by setting **disableHugoGeneratorInject = true**

Docsy seems to inject the generator meta tag **in each HTML head unconditionally**.

**Comment by fekete-robert** [comment]
You're right, I could reproduce the issue.

Unfortunately I can't fix it nicely, because if I set the disableHugoGeneratorInject at the top level of the configfile (as it should be), I can't reference the parameter from the template. If you add it under the params section, then you can disable it like this in the head.html partial:

`{{ if not .Site.Params.disableHugoGeneratorInject }}
{{ hugo.Generator }}
{{ end }}`

**Comment by chalin** [comment]
Oh, I hadn't realized that Docsy was _overriding_ Hugo's default behavior. I don't think that should be the case.

**Comment by nettozahler** [comment]
Exactly. Docsy is overriding the behavior described in https://gohugo.io/getting-started/configuration/. Thanks for the nice & quick PR. Regards...
