### ISSUE TITLE
Error executing "shortcodes/blocks/cover.html" at <.Fit>

### ISSUE THREAD

**Issue by sarahmaddox** [google/docsy#18]
Hallo to the Docsy team

I've just merged the latest version of Docsy into the Kubeflow website. When building the site after the merge, I got the following error:

```
$ hugo server -D
Total in 387 ms
Error: Error building site: "/home/sarahmaddox/github-repos/kubeflow/website-2/content/_index.html:19:1": failed to render shortcode "blocks/cover": "/home/sarahmaddox/github-repos/kubeflow/website-2/themes/docsy/layouts/shortcodes/blocks/cover.html:31:139": execute of template failed: template: shortcodes/blocks/cover.html:31:139: executing "shortcodes/blocks/cover.html" at <.Fit>: can't evaluate field Fit in type resource.Resource
```
I removed the following update from the file `themes/docsy/layouts/shortcodes/blocks/cover.html:31:139`:

```
         {{ with .Get "title" }}<h1 class="display-1 mt-0 mt-md-5 pb-4">{{ $title := . }}{{ with $logo_image }}{{ $logo_image_resized := (.Fit (printf "70x70 %s" $logo_anchor)) }}<img class="td-cover-logo" src="{{ $logo_image_resized.RelPermalink }}" alt="{{ $title | html }} Logo">{{ end }}{{ $title | html }}</h1>{{ end }}
```

And replaced it with the previous version of the line:

```
         {{ with .Get "title" }}<h1 class="display-1 mt-0 mt-md-5 pb-4">{{ . | html }}</h1>{{ end }}
```

The site now builds correctly.

The Docsy change was introduced in this PR:
https://github.com/google/docsy/pull/16/files#diff-ca2eecf7bb5b8a4697b935a9fd894fd5R30

This is the Kubeflow index file that the error refers to, and which uses the cover block:
https://github.com/kubeflow/website/blob/master/content/_index.html#L19

Here's my PR which merges the Docsy updates (except the line mentioned above) into the Kubeflow website:
https://github.com/kubeflow/website/pull/441

@ianlewis or anyone else who can help: Do you have any idea why we're getting the above error when merging this change into the Kubeflow site?

**Comment by ianlewis** [comment]
@sarahmaddox Thanks for the issue. Sorry about the error.

I think what is happening is that it's picking up the logo-jupyter.svg or logo-tensorflow.svg and trying to resize it but since it's svg it can't be resized.

The change I made in #16 was intended to act like the support for \*\*background\* image by looking for an image file that matches \*\*logo\*. A workaround would be rename the svg files to not include "logo" in the file name.

I'm open to better ways to add a logo image in the cover block that aligns with other support for images.  Kubeflow's website uses support for a logo in the navbar but it's limited to svg currently: https://github.com/google/docsy/blob/4dee12d1a704d7342473c17bab8b707102edd8b2/layouts/partials/navbar.html#L4

I'll be sure to test PRs w/ kubeflow's website in the future too.
