### ISSUE TITLE
Error deploying with Netlify if clone theme repo

### ISSUE THREAD

**Issue by frodriguezsmartclip** [google/docsy#184]
Hi again!

I've just wondered I'd like to customize this theme by my own.

So, I followed [this guide-part](https://www.docsy.dev/docs/getting-started/#cloning-the-docsy-theme-to-your-project-s-themes-subdirectory) cloning docsy theme inside my themes path.

BUT, I added this recursive part:

```
frodriguez@FRODRIGUEZ-PC MINGW64 /c/Hugo/Sites/docs-adtopy (master)
$ git clone --recurse-submodules --depth 1 https://github.com/google/docsy themes/adtopy
```

I think the part **--recurse-submodules --depth 1** is important, because it's not, not working... (I think)....

I changed the **"config.toml"** to new theme-name:

```
theme = ["adtopy"]
```

I tested on localhost running: 

```
hugo server
```

Works fine. Now, I am able to change i18n string on my own theme, change 404 error page... and more stuff.

Then, I went to Netlify for build and deploy automatic. So, I changed the  **build command** to this one:

```
cd themes/adtopy && git submodule update -f --init && cd ../.. && hugo
```
I tried also only with **build command** >hugo   but error again...

It's the same [like official docs](https://www.docsy.dev/docs/deployment/#deployment-with-netlify), BUT, I does not work... 😢 

The deploy log on Netlify say this:

> 2:36:54 PM: Build ready to start
2:36:55 PM: build-image version: 9cade8af58c2cf3a17a1e9433d2e979149488837
2:36:55 PM: build-image tag: v3.3.5
2:36:55 PM: buildbot version: 036f37945d6de439a17a554b3ae02e2f8f0f1fb0
2:36:56 PM: Fetching cached dependencies
2:36:56 PM: Starting to download cache of 375.3MB
2:36:58 PM: Finished downloading cache in 2.379054973s
2:36:58 PM: Starting to extract cache
2:37:05 PM: Finished extracting cache in 6.821951022s
2:37:05 PM: Finished fetching cache in 9.389474752s
2:37:05 PM: Starting to prepare the repo for build
2:37:05 PM: Preparing Git Reference refs/heads/master
2:37:06 PM: Error checking out submodules: fatal: No url found for submodule path 'themes/adtopy' in .gitmodules
2:37:06 PM: Failing build: Failed to prepare repo
2:37:06 PM: failed during stage 'preparing repo': Error checking out submodules: fatal: No url found for submodule path 'themes/adtopy' in .gitmodules
: exit status 128
2:37:06 PM: Finished processing build request in 10.970257925s

![Anotación 2020-01-29 145329](https://user-images.githubusercontent.com/59822855/73362713-a1381400-42a7-11ea-81ba-78277dd3a2d1.png)

The .gimodules in 'themes/adtopy' is the same like yours:

```
[submodule "assets/vendor/bootstrap"]
	path = assets/vendor/bootstrap
	url = https://github.com/twbs/bootstrap.git
[submodule "assets/vendor/Font-Awesome"]
	path = assets/vendor/Font-Awesome
	url = https://github.com/FortAwesome/Font-Awesome.git
```

The goal to achieve this is because I would like to do in the theme:

1. Customize the theme.
2. Not depends of others git modules
3. Customize i18n strings.
4. Change the theme's name for other.
5. Change the default 'content/en' to other 'content/custom_language' (es,it,... whatever)

**Any ideas to fix this issue??**  

**Maybe only is related to Netlify to the build command**... I dont know not works, because on localhost, the same commands, works fine... (ok, not kike "hugo server", but its works):

![Anotación 2020-01-29 145548](https://user-images.githubusercontent.com/59822855/73362694-94b3bb80-42a7-11ea-9f0e-a4a6bc4fc129.png)

Thanks a lot!! Regards 😃

**Comment by LisaFC** [comment]
OK, so the main problem with your deploy is that the theme *itself* is a submodule in the example project - the build instruction is telling Netlify to go look for your renamed theme as a submodule/external repo called "adtopy", which doesn't actually exist (this works fine if you're using the Docsy theme/name, as it knows where to find it)

If you want to have your own copy of the theme to customize/rename (rather than just add your own overrides), you'll need to not include it as a submodule and just clone the whole thing into your project: https://www.docsy.dev/docs/getting-started/#cloning-the-docsy-theme-to-your-project-s-themes-subdirectory

Just FYI, if you *can* use the Docsy submodule, you can do most of what you want to do with your theme with overrides or your config file:

- Customize the theme: you can override any bits of it you want in your own project. Here's an example I put together for another user that overrides the entire default page layout and some of the page partials in its own layouts/ directory: https://github.com/LisaFC/justdocs/tree/master/layouts
- Customize i18n strings: as above!
- Change the default 'content/en' to other 'content/custom_language' (es,it,... whatever): if I understand you correctly you can do this in your config.toml: https://www.docsy.dev/docs/language/

The only thing you can't do is rename the theme. You can possibly remove the Bootstrap and Font-awesome dependencies by generating your project resources locally (you'll need them locally to do this though) and then committing them to your repo, I used to have to do that on some older projects before Netlify supported "extended" Hugo.

**Comment by LisaFC** [comment]
Ah sorry, just saw you cloned the theme, that will teach me to not follow links.

OK, most of what I say above still applies. :)  Netlify is still looking for a theme submodule called "adtopy", while you're not actually using your cloned theme as a submodule. I'll see if I can get it to work myself, annoyingly the Hugo docs on cloning a single theme seem to have disappeared.....

I do still think you'd have a slightly easier time if you just overrode the bits of theme you want, as it means, for example, you'll be able to get any updates we make to Docsy by just updating the theme submodule.

**Comment by LisaFC** [comment]
OK, from experimenting with this further it looks like cloning the theme into your project is going to just cause a world of pain with Netlify continuous deployment unless you do a lot of Git messing around, as by default it's being treated as a separate repo inside your repo. One potential idea that might work better is to download the theme as a ZIP file and add it to your project as normal files (then you can just push them up to your source repo), but then you'd also have to download and unzip all of FontAwesome and Bootstrap and add those in too (under /assets/vendor/)

I'll consider removing that section from the docs, or at least just adding a big caveat that this won't work easily with Netlify.

**Comment by frodriguezsmartclip** [comment]
Hi Lisa, 

Ok, thanks for the reply!

Yeah, you're right in everything. So I decided still use theme/docsy as submodule.

Make custom layouts inside: ✔️ 

- /root/layout/__custom__layout

Make custom assets inside: ✔️ 

- /root/assets/....

Make custom language strings inside: ✔️ 

- /root/i18n/__language_name
- edit config.toml and modify

```
[languages]
[languages.it]
title = "Whatever"
description = "Description foo"
languageName ="Italian"
weight = 1
```

Is there any more other custom way to modify the theme without touching the real one/clonned "theme/docsy"??

I think in this [docs site it's everything well explained.](https://www.docsy.dev/docs/adding-content/)

Still using the build command for Netlify. (works like a charm)

Because I wanted to use your theme but hosted by myself, BUT, I see it's a little difficult to work... So, it's ok and working fine as it's right now.

Maybe, in a near future, might have some sense....

BTW, Thanks for the reply and help!!! 👍 

Have a nice day 😉

**Comment by LisaFC** [comment]
Glad to help and glad it's working properly for you!

> Is there any more other custom way to modify the theme without touching the real one/clonned "theme/docsy"??

Yes, you can add your own partials, shortcodes, add your own SCSS, etc. etc., anything that's in the theme can be customized. Basically just have them in your own project and they'll override/add to any equivalent in the Docsy theme.
