### ISSUE TITLE
Wrong gcs_engine_id format in documentation or missing explanation.

### ISSUE THREAD

**Issue by sorenwacker** [google/docsy#1999]
The [docs](https://www.docsy.dev/docs/adding-content/search/) explain to use the `gcs_engine_id` in the following format:
```
[params]
# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "011737558837375720776:fsdu1nryfng"
```

However, the format of the id comming from Google is more like this `jd5pmoj434q9vew3j` 17 characters lower letters and numbers. 

Is this an old format or where do you get this format from?

**Comment by chalin** [comment]
Hi. FYI, that's the format of the ID actively being used by the Docsy User Guide, so it is a valid format, see: https://github.com/google/docsy/blob/f4c7e2212843a0af159ec6e8ed49561a98ebdb05/userguide/hugo.yaml#L63

Give your (shorter) ID a try, and if it works, then you'll be all set.

**Comment by sorenwacker** [comment]
It does not work. The page is indexed, but the page returns no search results.

**Comment by chalin** [comment]
> It does not work. The page is indexed, but the page returns no search results. Were do one obtain this ID, maybe I am looking at the wrong place.

@emckean - can you provide guidance here?

**Comment by sorenwacker** [comment]
Seems someone closed this.

**Comment by chalin** [comment]
Yes, as you know I closed this issue because format of the ID is valid -- as mentioned in https://github.com/google/docsy/issues/1999#issuecomment-2111203896. I could add a note to the User Guide to the effect of "your ID could differ", but I (and the other Docsy maintainers) are swamped with higher priority items. If you post a question to the discussion forum, then maybe a community member can help you debug your GCS issues. Otherwise, you'll have to turn to other forums. Good luck!
