### ISSUE TITLE
No search results with gcs_engine_id.

### ISSUE THREAD

**Issue by sorenwacker** [google/docsy#2013]
### Environment

- [x] Version of Docsy you are using: v0.10.0
- [ ] How are you using Docsy? As a:
  - [x] Hugo module
  - [ ] NPM module
  - [ ] Git submodule
  - [ ] Other:
- [x] Version of Hugo you are using (output of `hugo version`): 
```yaml
image: registry.gitlab.com/pages/hugo/hugo_extended:latest
```
- [x] OS:
  - [x] Linux
  - [ ] macOS
  - [ ] Windows
  - [ ] Other:

### Problem

```
[params]
gcs_engine_id = "jd5pmoj434q9vew3j"
```

`/content/search.md`:
```
---
title: Search results are currently under construction.
layout: search
---
```

The page was indexed by google, and the search bar shows up, but no search results are shown.

**Comment by chalin** [comment]
As I mentioned in https://github.com/google/docsy/issues/1999#issuecomment-2134590373, I suggest that you "post a question to the Docsy discussion forum, then maybe a community member can help you debug your GCS issues. Otherwise, you'll have to turn to other forums. Good luck!"

Closing since this is, IMHO, a GCS issue, not a Docsy issue.
