### ISSUE TITLE
Mobile view with the sidebar search disabled

### ISSUE THREAD

**Issue by tshort** [google/docsy#211]
With `sidebar_search_disable = true`, the mobile view loses the search bar and the navigation icon. The navigation icon is most important.

In Lunr and Algolia, the sidebar isn't supported, so this is probably a common setup. 

Any suggestions on how to improve the mobile view?

**Comment by LisaFC** [comment]
Just FYI sidebar search is now supported with Lunr, but yes, agree we need to make sure we provide a good experience on mobile without it.

If you have one handy, do you have an example of a site without a sidebar search so I can see what it looks like in Mobile?  Otherwise I'll spin one up myself when I have a moment.  I don't think we intended for the nav icon to disappear as well but that is not to say that's not what happens. :)

**Comment by tshort** [comment]
Sorry, I don’t have a public site with the sidebar disabled.

**Comment by LisaFC** [comment]
No problem, I can put together a little demo and see what I can fix!

**Comment by LisaFC** [comment]
Yep, you're right, the navigation isn't appearing, I'll try to fix that.

**Comment by frodriguezsmartclip** [comment]
I suscribe to this thread, I need this too. Thanks @LisaFC  😉

**Comment by LisaFC** [comment]
Fixed in #297
