### ISSUE TITLE
Turn off anchor symbol on headings

### ISSUE THREAD

**Issue by pwinston** [google/docsy#254]
When viewing a page with headings if you hover over a heading a little anchor/chain-link symbol pops up. There there a way to disable these so nothing pops up?

**Comment by wrex** [comment]
Personally, I *really* like that feature. It let's you know there is a named anchor (id) on every header (right click to copy the link). The link you copied will refer others to that specific heading rather than to the top of a long page. 

Some themes leave an anchor symbol up all the time rather than just on hover (which I find ugly and annoying). I think docsy's trick of only showing it on hover gets the UX exactly right.

If you really want to disable it, though, I think you just need to create an empty file in `assets/js/anchor.js`.

**Comment by frodriguezsmartclip** [comment]
Hi, Where can this feature be enabled or disabled?  I realized I have realized that I have it disabled (I don't know why ...).

Thanks!

**Comment by LisaFC** [comment]
We added it in #123 but we didn't put an opt-out switch in the first iteration.  You can, as wrex says, remove it by just overriding the .js with a blank file. Though if people want to toggle it in config we can leave this issue open to add a conditional somewhere.

If the anchors *aren't* appearing and you want them you may be using an old version of the theme?

**Comment by wrex** [comment]
> Hi, Where can this feature be enabled or disabled? I realized I have realized that I have it disabled (I don't know why ...).

Other than an old copy of the theme, the only reasons I can think of for the magic link-thingy not to show are if Javascript is disabled in the browser or hover state isn't supported (e.g. phones or tablets).

**Comment by frodriguezsmartclip** [comment]
Mmmmm I think was problem of Netlify...

I changed "jquery-v3.3.1/jquery.min.js" to new version without vulnerabilities "jquery-v3.4.1/jquery.min.js" and works fine everything.

Yes, I have configured well the site with custom anchor symbol on heading on my custom partials theme.

Thanks a lot!! Regards ;)

**Comment by pwinston** [comment]
Creating a blank file `assets/js/anchor.js` turned them off, which is what I wanted. The feature is is nice in some ways, but on this site in particular isn't appropriate. Thanks!
