### ISSUE TITLE
Swagger layout not using baseURL

### ISSUE THREAD

**Issue by chammock** [google/docsy#278]
We have our docs deployed to gitlab pages with the hugo baseURL defined as `/groupname/project` and everything currently works fine. I then added the `swaggerui` shortcode and it renders locally but not once deployed. The deployed version is trying to reference the gitlab root url vs the baseURL defined by hugo.

I downloaded the final deployment package and noticed that the [href](https://github.com/google/docsy/blob/053672c24cf51417c300f8ea5d32db545340746d/layouts/swagger/baseof.html#L6) in the swagger layout was unchanged.

Actual:
```
<link rel="stylesheet" type="text/css" href="/css/swagger-ui.css">
```
Expected:
```
<link rel="stylesheet" type="text/css" href="/groupname/project/css/swagger-ui.css">
```

Any suggested fix?

**Comment by LisaFC** [comment]
@theletterf, you added this layout, can you figure out what's going on? I'll take a look too.

**Comment by quickstar** [comment]
I think the problem is related in https://github.com/google/docsy/blob/master/layouts/swagger/baseof.html

For example on line 6 the css is loaded like: `<link rel="stylesheet" type="text/css" href="/css/swagger-ui.css">` which doesnt' respect the baseUrl.

I could easily fix this, but I don't know how to access the baseUrl in this context! Any suggestions?

**Comment by quickstar** [comment]
Pull request created: https://github.com/google/docsy/pull/367
