### ISSUE TITLE
Update "Getting Started"

### ISSUE THREAD

**Issue by Benjamin-Philip** [google/docsy#369]
In [Getting Started](https://www.docsy.dev/docs/getting-started/#linux), I found the following error:

> Do not use sudo apt-get install hugo, as it currently doesn’t get you the extended version.

This doc is clearly outdated as `sudo apt install hugo`  installed v0.74.3 for me.
Requesting to update the docs.

**Comment by LisaFC** [comment]
Is it v0.74.3 extended, though? If it's not hugo_extended you don't have SCSS support and we use SCSS for styling.

It would be nice if it got the latest extended version, I think when I wrote the doc it was both not the extended version and old....

**Comment by Benjamin-Philip** [comment]
Everything is fine - it works, I just meant that you should update the docs, because as a user, I don't want to be trying to use an obsolete feature, or miss out on a new feature which may be useful. I hope you get what I mean - Everything I have done so far
works well, but I would like some updated info on configuring the theme.

**Comment by LisaFC** [comment]
Right, what I meant was that there are multiple packaged binaries for each Hugo release and only some of them (the ones marked _extended) have SCSS support. If the one you got with sudo apt-get works with our theme, then that's great! I'll check it myself and update the docs.

**Comment by LisaFC** [comment]
Ok, it looks like it doesn't get you the extended version on all platforms: https://gohugo.io/getting-started/installing/#debian-and-ubuntu (it didn't for me), so I'll update the docs saying that it *might* get you an appropriate version rather than it won't (also the Hugo docs themselves recommend against using this approach because it's still quite a bit behind the latest version, which is currently 0.78.1)
