### ISSUE TITLE
Navbar is not responsive

### ISSUE THREAD

**Issue by tommyblue** [google/docsy#376]
Hi, the top navbar doesn't behave correctly on mobile. 

We have 7 elements + the search form and it doesn't collapse. Users are required to scroll it, but it's counterintuitive on mobiles.

As docsy is based on bootstrap, making it collapsible doesn't require any new code. I made a short test using the vanilla code from the bootstrap website and it works.
But I see the `js-navbar-scroll` that enables the horizontal scroll, maybe I'm missing some feature here?
is there a way to remove it and enable the default bootstrap behaviour? Something like a configuration option would be great.

Thanks :slightly_smiling_face:

**Comment by LisaFC** [comment]
Sure, I'll have a look. You'd end up with a hamburger menu button (for the top nav) above a hamburger menu button (for the left nav) in docs sections if you collapsed it, though, which can look a bit odd. The Bootstrap site itself uses scrolling rather than collapsing for their top nav on mobile.

Also the search form shouldn't appear in the top nav on mobile anyway, it pops down to above the text (it's actually the one from the left nav...).

**Comment by fschrempf** [comment]
I'm having the same issue. The horizontal scrolling for the menu on narrow screens would be ok, if there is some indication to the user that it's scrollable. Maybe a blur effect and/or arrows to the right and left if scrolling is possible in these directions?

Or a hamburger button would be fine for me too, as the sidebar is disabled anyway in my case.

**Comment by tommyblue** [comment]
maybe the easiest solution (I don't know how feasible) would be to allow the users to completely override the navbar creating a layout file, so they're free to use the included navbar or a custom version.
In our case, for example, we'd like to use the hamburger but also leave 1 or 2 entries always visible

**Comment by emckean** [comment]
Is this still an issue after updating to the newest Docsy version (with the newest Bootstrap)?

**Comment by chalin** [comment]
Closing. Feel free to open a new issue of you feel that the problems persist with the latest version of Docsy.
