### ISSUE TITLE
Deploying to Netlify settings

### ISSUE THREAD

**Issue by prdsoftware** [google/docsy#404]
I'm having real trouble trying to get Docsy working with Netlify.  I can build the site locally on my machine, but Netlify has the following build error:

Error: Error building site: POSTCSS: failed to transform “scss/main.css” (text/css): resource “scss/scss/main.scss_4853eb546e7a6c0898ed71feae7357c0” not found in file cache

The Docsy documentation for Netlify has confused me.  In the deployment section https://www.docsy.dev/docs/deployment/ at 3.1 is says to use this command..

> cd themes/docsy && git submodule update -f --init && cd ../.. && hugo

but the example netlify.toml file at https://github.com/google/docsy/blob/master/netlify.toml includes a directive to install postcss and uses this command...

> git submodule update -f --init && cd userguide && npm install postcss-cli && hugo --themesDir ../.."

and in the installation doco at https://www.docsy.dev/docs/getting-started/#using-the-theme is says to also install the autoprefixer

sudo npm install -D --save autoprefixer
sudo npm install -D --save postcss-cli

So, 3 different versions of what to install.

Any ideas? Thoroughly confused! :-)

**Comment by LisaFC** [comment]
So the reason why the Docsy site command is weird is because the Docsy user guide site root is *inside* the Docsy theme so you need to specify that its theme dir is *outside* the site. For a regular site you don't need the --themesDir flag because the theme directory is where Hugo expects it to be.

Let me check about the adding postcss on the Netlify servers, this might be something that we had to update in our config and we forgot to update the docs (or vice versa) - I have a dim memory that postcss stopped working as a global install recently so you have to add it to every directory where you want to use it. Does Netlify work for you if you add the npm install to your build command?

**Comment by prdsoftware** [comment]
Hi Lisa,

Thanks for the reply.  No, Netlify doesn't work with my current build settings (although that could be part of the issue).  My build command looks like this...

**cd themes/docsy && git submodule update -f --init  && npm install autoprefixer && npm install postcss-cli && cd ../.. && hugo**

The Netlify logs indicate that the packages are updated/installed, but I'm getting dependency warnings.

> 11:37:25 PM: npm WARN autoprefixer@10.1.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
> 11:37:25 PM: npm WARN postcss-cli@8.3.1 requires a peer of postcss@^8.0.0 but none is installed. You must install peer dependencies yourself.
> 11:37:25 PM: npm WARN postcss-reporter@7.0.2 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies 

later in the log I get...

> 11:37:25 PM: + postcss-cli@8.3.1
> 11:37:25 PM: added 92 packages from 63 contributors and audited 112 packages in 4.497s
> 11:37:26 PM: 13 packages are looking for funding
> 11:37:26 PM:   run `npm fund` for details
> 11:37:26 PM: found 0 vulnerabilities
> 11:37:26 PM: Start building sites …
> 11:37:42 PM: WARN 2020/12/31 12:37:42 found no layout file for "JSON" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> 11:37:42 PM: Total in 16790 ms
> 11:37:42 PM: **Error: Error building site: POSTCSS: failed to transform "scss/main.css" (text/css): resource "scss/scss/main.scss_4853eb546e7a6c0898ed71feae7357c0" not found in file cache**

Thanks and best regards, 
Rod

**Comment by prdsoftware** [comment]
> so you have to add it to every directory where you want to use it. 

Can you suggest where Docsy requires it?  What folder should I be in when I run the npm install postcss-cli command?  Do I have to do this in multiple folders?  I don't know what Docsy requires.

**Comment by prdsoftware** [comment]
I still can't get this going on Netlify.  When you install postcss-cli, which directory do I need to be in when I run the command?  The hugo structure, or the themes/docsy structure?...or both?...somewhere else?

I even tried checking in all of the node-modules folder from my local machine so that Netlify would have the dependencies it needs.  Still no go - same error "Error: Error building site: POSTCSS: failed to transform "scss/main.css" (text/css): resource "scss/scss/main.scss_4853eb546e7a6c0898ed71feae7357c0" not found in file cache"

Everything builds fine on a local machine.  Both "hugo server" and "hugo" commands build on a local machine.  Move the whole thing to Netlify and it fails.

Not sure where the problem is.  With Docsy, Netlift, or some config somewhere.  Without consistent documentation, this is almost impossible to diagnose and fix for me.

Any help greatly appreciated.

**Comment by prdsoftware** [comment]
OK, so finally got it going on Netlify by installing postcss.  

The Docsy documenation doesn't mention this as a dependency for Netlify explicitly (that I could see).  It mentions postcss-cli only.

Thanks anyway.
Rod

**Comment by LisaFC** [comment]
Ah glad you got it working (and sorry for the late reply, I've been moving house...). 

I will dig in to this a bit because the build command for the Docsy-Example site on Netlify (I just checked) is still

```
cd themes/docsy && git submodule update -f --init && cd ../.. && hugo
```

...and it's building perfectly. It may only now need postcss installed on Netlify for a first build or if you're changing the CSS. I'll find out and update the docs accordingly!

**Comment by LisaFC** [comment]
Can you share the repo you're using just so I can have a look?

**Comment by LisaFC** [comment]
Thanks! I'm also going to try and put a new site of my own up and see what happens....

**Comment by prdsoftware** [comment]
No worries.  The doco is not really complete at this stage - been migrating it from an old compiled HTML help file, so it's still got a lot to go and broken links/images etc....but making some progress now.

**Comment by LisaFC** [comment]
OK, so I just copied the Docsy example site:
https://github.com/LisaFC/boing

...and stuck it up on Netlify with that build command and the latest version of Hugo, and voila:
https://tender-beaver-c94732.netlify.app/

Now I need to remember why Past Me had to update the Netlify settings with postcss-cli for the Docsy user guide (other than the weird location of the theme dir) and figure out why your site is different....

**Comment by RichieEscarez** [comment]
Im still on version 6 but I found in in the changelog that is says post v8, you need to install POSTCSS separately (https://github.com/postcss/postcss-cli/blob/master/CHANGELOG.md). Hopefully that leads you down the right path?

**Comment by prdsoftware** [comment]
Thanks Richie, yes, that's how I got it going - by installing PostCSS separately.  The hugo compile errors were telling me that all along (in a dev-like way), but I was relying too much on the Docsy install instructions that were out-of-date.  Thanks, Rod

**Comment by RichieEscarez** [comment]
FYI, ive added mention of installing postcss for v8 + versions here https://github.com/google/docsy/pull/410

**Comment by LisaFC** [comment]
Richie you're a genius - I just bumped the postcss version from the test site I put up on Netlify from 7.1 to 8.0 and it fell over with exactly the same error. Downgraded to 7.1 again and it ran perfectly.  It's a fairly new update which is why I think nobody else has hit it yet (the Docsy example site is on 7.1.2 I think) and why the docs haven't been updated yet.

(I think the Netlify settings for the Docsy user guide are a bit of a red herring, because for that site the only reason we have to install postcss separately is because it's in a weird directory relative to the repo root)

**Comment by LisaFC** [comment]
Also if I updated my package.json to include both postcss *and* postcss-cli, it also built on Netlify. Hoorah!

```
  "devDependencies": {
    "autoprefixer": "^9.8.6",
    "postcss-cli": "^8.0.0",
    "postcss": "^8.0.0"
  }
```

Will update the Netlify instructions.

**Comment by chalin** [comment]
Closed by

- #412
