### ISSUE TITLE
Sidebar tree show only 50 links

### ISSUE THREAD

**Issue by ydcool** [google/docsy#426]
Source code here:

https://github.com/google/docsy/blob/196e4cd93da3091d02b74ceb12b172e780e11235/layouts/partials/sidebar-tree.html#L44

Why limit to 50 links in sidebar tree so that there's no way to navigate to pages more than 50 ?

**Comment by LisaFC** [comment]
Let me take a look, I *think* it was because more than 50 pages at a given level was hard to scroll/navigate (The Neverending Sidebar Of Doom) and also may have affected render speed. You can have more than 50 pages total in a nested structure no problem, and there are lots of Docsy sites with bigger page counts in a single left nav (eg https://www.kubeflow.org/docs/)

You can always override that file for your project if you want to up the limit in the meantime.

**Comment by ydcool** [comment]
I see, thanks for your reply
