### ISSUE TITLE
Including material from directories outside of the docsy project

### ISSUE THREAD

**Issue by Symbolics** [google/docsy#440]
Just spent some time learning how to do "include", only to find that readFile.md was implement #162 in in the theme when I went to implement it myself.

**Comment by Symbolics** [comment]
Does "include" work with relative paths? In this use case we have documentation in one folder, and would like to pull in documentation from project level folders that exist at the same level in order to build up the reference library.

I've tried both absolute paths and relative to site root (e.g. "../num-util/docs/README.md"), but none work. I'm on Windows, in case this make a difference.
```
ERROR 2021/02/02 18:05:28 "S:\src\documentation\content\en\docs\Reference\Numerical-Utilities.md:9:1": failed to render shortcode "readfile": failed to process shortcode: "S:\src\documentation\themes\docsy\layouts\shortcodes\readfile.md:7:12": execute of template failed: template: shortcodes/readfile.md:7:12: executing "shortcodes/readfile.md" at <readFile>: error calling readFile: file "..\\num-utils\\README.md" does not exist
```
The file does exist (relative to the site root):
```
$ pwd && ls ../num-utils/README.md
/s/src/documentation
../num-utils/README.md
```

**Comment by LisaFC** [comment]
So the shortcode uses Hugo's readfile function (documented here: https://gohugo.io/functions/readfile/), which specifies that the filename must be relative to the current project working directory, or the project’s /content folder, if that helps.

@RichieEscarez, do you have a usage example to share? Also do you want to add the readfile shortcode to the "helper shortcodes" section in our docs, given that you wrote it?

**Comment by RichieEscarez** [comment]
By default, `readFile` does not work with relative paths. Generally, Hugo is designed around root paths ([the path from within your `content` folder](https://gohugo.io/content-management/organization/#organization-of-content-source)). 

You can create a custom shortcode for your site that incorporates the existing `readFile` function and uses your relative URLs.

For Knative, I wrote a custom shortcode with logic (based on the way we use relative paths) to first determine the root path of a file, and then pass that root path to the `readFile` function (you override a file by placing that file in the same folder and using the same filename in your site): https://github.com/knative/website/blob/master/layouts/shortcodes/readfile.md
Note: In responding here to this issue, I learned something new today and see that Hugo now supports [nested shortcodes](https://gohugo.io/content-management/shortcodes/#nested-shortcodes). The Knative `readfile` linked here does not include that support as it is (and does not support nested shortcodes).

Otherwise, as explained in [PR#8](https://github.com/google/docsy/pull/8), you need to specify the path to a file that lives within your `content' folder.

If your Hugo site lives under: 
**`S:\src\documentation\`**

Then you need to move `num-utils/README.md` to a location under 
`S:\src\documentation`**`\content\`**

For example, if you move it to:
`S:\src\documentation\content`**`\example\`**

Then your function call is:
`{{% readfile file="/example/num-utils/README.md" markdown="true" %}}`

Another point to keep in mind is that by default, the menu reads all folders and files. Therefore, files that you only use for "includes" will also render in the menu unless you explicitly hide that content, for example: [config.yaml](https://gohugo.io/getting-started/configuration/#ignore-content-files-when-rendering) or [modify the menu logic](https://discourse.gohugo.io/t/exclude-page-from-menu/16166)

**Comment by Symbolics** [comment]
When you say "by default", are there non-default options to work with relative paths?

Each of the systems I'm trying to pull in under the docs/Reference/ directory are stand-alone and also published independently. If they are moved under the Hugo root directory, they won't be 'close' to the project any more, and the docs would have to be sync'ed somehow with the main project folder's docs/ directory. I'd like to avoid this if it's possible.

Is there any other way to refer to content outside of the Hugo root directory?

**Comment by LisaFC** [comment]
I haven't seen any way of getting Hugo to pull in content that isn't under your project root somewhere, no.

You might get some more suggestions from the people in the Hugo discussion forum, as that has lots of Hugo power users and they often have very useful suggestions: https://discourse.gohugo.io/

**Comment by RichieEscarez** [comment]
> When you say "by default", are there non-default options to work with relative paths?
No sorry about the confusion (by default = out of the box). I mean to say, that you always have the option to override a file (shortcode, etc) and change the behavior of any given shortcode on your site (see the Knative version of our `readfile` above).
> 
> Each of the systems I'm trying to pull in under the docs/Reference/ directory are stand-alone and also published independently. If they are moved under the Hugo root directory, they won't be 'close' to the project any more, and the docs would have to be sync'ed somehow with the main project folder's docs/ directory. I'd like to avoid this if it's possible.
> 
> Is there any other way to refer to content outside of the Hugo root directory?
With Hugo and the Docsy template "out of the box", your only option to refer to that external content is to simply link to it. Otherwise you need to write custom scripts to make those files available to where Hugo looks when it builds your site.
More about the "content" folder is explained here: https://gohugo.io/getting-started/directory-structure/#directory-structure-explained

**Comment by Symbolics** [comment]
So, the easiest way to do this would be to symlink to the files you want to include. Apparently this works on Unix, but not on Windows, despite Windows having first class symlinks. So the alternative, and apparently recommend way, ([according to bep](https://discourse.gohugo.io/t/alternative-to-symlinks/19254)), is by using the [module facility](https://gohugo.io/hugo-modules/configuration/#config) and mounting the directories. Quick example:

In my environment, everything lives under S:/src:
```
s:/src/project-a
s:/src/project-b
s:/src/documentation
```
I want to pull in the docs/ directories for all the subprojects so they get built into an overarching documentation site by Hugo. In this case, the project documentation is auto-generated API docs, and the s:/src/documentation contains human generated content (tutorials, examples, etc). So to have this API documentation appear under your Reference section, create a module mount for each of the projects:
```
[module]
  [[module.imports]]
    path="S:/src/"
  [[module.imports.mounts]]
    source="project-a/docs"
    target="content/docs/Reference/project-a"
    language="en"
  [[module.imports.mounts]]
    source="project-b/docs"
    target="content/docs/Reference/project-b"
    language="en"
```
Bob's your uncle.

You need to add the front matter to the project documentation files.

**Comment by LisaFC** [comment]
Oh really glad you found a solution! It's a slightly "niche" problem but may come up again - I wonder if I can even find somewhere in the docs to link to this issue and/or the relevant Hugo docs.
