### ISSUE TITLE
Question: Using Prism Highlighting in Markdown

### ISSUE THREAD

**Issue by alexfornuto** [google/docsy#498]
I'm not sure if this is a question for Docsy, ~Blackfriday~ Goldmark, Hugo, or other so apologies in advance.

I've been attempting to use the [Line Highlight](https://prismjs.com/plugins/line-highlight/) Prism plugin in my Docsy-themed docs site. After overriding the js and css, I'm unsure of how else to enable it, and/or how to invoke it in my Markdown.

The plugin page indicates that it's invoked by adding a `data-line` value into the `pre` tag. How is this translated into Markdown? And if this is documented and I missed it, please tell me where so I can look there and not bother any one next time.

**Comment by LisaFC** [comment]
Hmm, from looking at the docs it seems that you have to specify it in HTML - you have to add an attribute to the code block and Goldmark doesn't support adding custom attributes to Markdown elements (except headers).

You could always use `pre` just for the code snippets you want to highlight - if you have `unsafe = true` in the Goldmark settings in your config.toml you can have HTML elements in your Markdown pages (I tend to do it for large tables because Markdown tables are horrible).

Might be worth going to the Hugo forums to see if anyone else has used it? https://discourse.gohugo.io/

**Comment by alexfornuto** [comment]
@LisaFC thanks for the info! Out of curiosity, if I were to switch the product to using Blackfriday instead of Goldmark, would I be able to add a shortcode for this plugin? If so, is there a syntax for that documented?

If not, I'll just borrow the [shortcode](https://github.com/panr/hugo-theme-terminal/blob/master/layouts/shortcodes/prismjs.html) from hugo-theme-terminal.

**Comment by alexfornuto** [comment]
P.S. [this doc](https://gohugo.io/getting-started/configuration-markup/) from gohugo.io indicates that Goldmark should support line highlighting, but I'm unable to replicate the example.

**Comment by LisaFC** [comment]
I don't think Goldmark natively supports line highlighting - the "highlight" bit of the config is for code highlighting with Chroma ie using different colours for different syntax elements.

That page does say that in the most recent version of Hugo they've introduced supporting custom attributes in Goldmark for elements that aren't headers, is that the bit you meant?

**Comment by alexfornuto** [comment]
> That page does say that in the most recent version of Hugo they've introduced supporting custom attributes in Goldmark for elements that aren't headers, is that the bit you meant?

Yes, that's what I meant. Not sure what the syntax is to apply those elements.

**Comment by LisaFC** [comment]
I think something like: 

\``` {data-line="2"}
lovely code;
more lovely code;
\``` 

should be equivalent to

\<pre data-line="2">
...
\</pre>

Also I've just realized that Chroma (Hugo's default syntax highlighter) also supports line highlighting without the need for a plugin, so if you're not wedded to Prism: 

\```go {.myclass linenos=table,hl_lines=[8,"15-17"],linenostart=199}
// ... code
 \```

...or in earlier versions of Hugo: https://gohugo.io/content-management/syntax-highlighting/#highlight-shortcode

**Comment by alexfornuto** [comment]
Unfortunately 

> ``` {data-line="2"}
> lovely code;
> more lovely code;
> ```

doesn't work as expected. The project uses hugo 0.82.0, which I _think_ is relatively new. And while I'm not wedded to prism myself, I'm new to the project so I'm trying to implement the features I want with the least amount of systemic change.

**Comment by LisaFC** [comment]
Yeah, I've been playing around with it for a bit and I can't get it to work - I think the problem is that if you add the attributes to your fenced code block, the generated HTML actually has the attributes on the \<div> rather than the \<pre> inside it, which is not what the Prism CSS/JS is expecting. So I think if you stick with Prism and want to use this feature you'd need to  use raw HTML for the relevant blocks.

You might get more useful input on the Hugo forums as there are probably people using Prism on sites with other themes.

**Comment by alexfornuto** [comment]
Fair 'nuff. Thanks for all your input!
