### ISSUE TITLE
KaTeX delimiters to parse GitLab Markdown

### ISSUE THREAD

**Issue by simonspa** [google/docsy#564]
I'm trying to configure KaTeX delimiters in order to parse and interpret the (admittedly odd) GitLab Markdown style using fenced code blocks of type `math` for formulae:

https://docs.gitlab.com/ee/user/markdown.html#math

I have added the definition to my `config.toml` but it doesn't seem to do anything - maybe because code highlighting is performed before KaTeX parsing?

```
[[params.katex.options.delimiters]]
left = "```math"
right = "```"
display = true
```

Do you have an idea how I could make the two compatible?

**Comment by LisaFC** [comment]
@deining, any ideas?

**Comment by deining** [comment]
Having a look at the [documentation](https://katex.org/docs/autorender.html) of the autorender extension, the `ignoredTags` option looks interesting to me: The default value of this option is ["script", "noscript", "style", "textarea", "pre", "code", "option"]. Since your code block is wrapped inside `<pre>` and `<code>` tags, the content of your code block might be ignored by the autorender extension. Just an idea, I haven't tested this. Maybe this can bring you on the right track here.

**Comment by simonspa** [comment]
Thanks @deining for the suggestion! I have tried this but unfortunately to no avail. After configuring KaTeX with

```toml
[params.katex.options]
ignoredTags = ["script", "noscript", "style", "textarea", "option"]

[[params.katex.options.delimiters]]
left = "```math"
right = "```"
display = true
```

my HTML still has the bare code:

```html
<pre><code class="language-math" data-lang="math">\chi (x) = e^{-t/\tau}</code></pre>
```

I've also tried to find other solutions that use KaTeX with GitLab-flavored markdown but the only project I have found is this Python wrapper for KaTeX:

https://github.com/mbarkhau/markdown-katex

As far as I can see and understand the code, they parse the MD independently and only pass the stripped content to the KaTeX renderer. Do you have any other idea? (It's really unfortunate GitLab had to go their individual path there instead of sticking to what everyone else uses...)

**Comment by deining** [comment]
With #987, support for GLFM math blocks was added.
Therefore this ticket can be closed.
