### ISSUE TITLE
Icons Flickering when devtools open

### ISSUE THREAD

**Issue by ColdHeat** [google/docsy#681]
I'm not sure what the cause of this is but it looks like whenever the Chrome Devtools are open the icons in docsy will grow and flicker making it really annoying to debug. Does anyone else experience this or have an idea where the issue might be? 

https://user-images.githubusercontent.com/166333/132561009-1ec8c047-181f-44bf-a6ab-0a5f6bdfb5d5.mov

To be clear, I have devtools open in another window but I can put it in the same window to make it clearer if needed.

**Comment by LisaFC** [comment]
Waaaaaah, that's very weird. Let me see if I can reproduce it.

**Comment by LisaFC** [comment]
So I opened Chrome Devtools with [docsy.dev]() (which has icons in the top nav) and it didn't do anything odd. Is it happening with any other Docsy sites (like our one, or anything on the Examples page), or just your own site.

**Comment by ColdHeat** [comment]
I think this only happens locally if Hugo is reloading the page. Could you perhaps try with https://github.com/CTFd/docs or with a local checkout of docsy?

**Comment by LisaFC** [comment]
So I don't have `hugo` on a local machine right now but what I think is happening is that the svg images are being (briefly) rendered without any styling, which happens if the CSS for them hasn't loaded yet.

By default when you run `hugo server` you get a quick dev build of the site, and in our case that involves not having preloaded CSS: https://github.com/google/docsy/blob/master/layouts/partials/head-css.html - I think in most cases it's not slow enough to make a difference, and I'm not sure why having devtools open is pushing it over the edge, but...

If you run `hugo server -e production`, you'll get a production build with preloaded CSS before the page renders, which I hope will stop the flickering. Let me know!

**Comment by LisaFC** [comment]
Did that fix the problem?

**Comment by ColdHeat** [comment]
I actually get a different error:

```
❯ hugo server -e production
Built in 669 ms
Error: Error building site: POSTCSS: failed to transform "scss/main.css" (text/css): resource "scss/scss/main.scss_4853eb546e7a6c0898ed71feae7357c0" not found in file cache
```

Whereas hugo server still works:

```
❯ hugo server

                   | EN
-------------------+------
  Pages            |  92
  Paginator pages  |   0
  Non-page files   |   0
  Static files     | 151
  Processed images |   0
  Aliases          |   0
  Sitemaps         |   1
  Cleaned          |   0

Built in 730 ms
Watching for changes in 
Watching for config changes in 
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

**Comment by ColdHeat** [comment]
Ah I see this is a different error https://github.com/google/docsy/issues/235

**Comment by ColdHeat** [comment]
Yes this seems to work much better. Thanks for the guidance!
