### ISSUE TITLE
Print layout is leaving wide right margin

### ISSUE THREAD

**Issue by tjdavis3** [google/docsy#688]
When printing docs pages, whether from Ctrl-P or "Print entire section" the page looks fine when rendered, but when printed (print preview, saving as PDF, etc) there is always a wider right margin.  It appears as if the stylesheet might be leaving the space for the right-side navigation which isn't shown.

**Comment by LisaFC** [comment]
@gwatts, any ideas?

**Comment by gwatts** [comment]
Been a while since I've had time to keep up with Docsy, but running `git bisect` reveals that commit https://github.com/google/docsy/commit/bf5cde8cee4cbfaef7a983de3af0dc264b4e73f9 seems to have had some unfortunate side effects for the margins etc for the print view

Will take a closer look asap unless @narrenfrei can take a quick look as the author of that particular commit?

**Comment by gwatts** [comment]
@tjdavis3 / @LisaFC can you test the referenced PR when you have a moment?
