### ISSUE TITLE
Unable to check out submodules

### ISSUE THREAD

**Issue by killermoehre** [google/docsy#822]
Hi,

after a fresh `clone` I hit following error for checking out the submodules

```shell
$ LANG=C git clone https://github.com/google/docsy.git
$ LANG=C git submodule update --init --recursive --remote --force
Submodule 'assets/vendor/Font-Awesome' (https://github.com/FortAwesome/Font-Awesome.git) registered for path 'assets/vendor/Font-Awesome'
Submodule 'assets/vendor/bootstrap' (https://github.com/twbs/bootstrap.git) registered for path 'assets/vendor/bootstrap'
Submodule path 'assets/vendor/Font-Awesome': checked out '7cbd7f9951be31f9d06b6ac97739a700320b9130'
fatal: Needed a single revision
fatal: Unable to find current origin/v4-dev revision in submodule path 'assets/vendor/bootstrap'
```

As we use `docsy` as submodule in our own Hugo repo, this is quite annoying as we can't build our site.

**Comment by deining** [comment]
> Hi,
> ...
> ```shell
> $ LANG=C git submodule update --init --recursive --remote --force
> ```

Why are you using the --remote option?

Simply omit this option and it will work:

```shell
git submodule update --init --recursive

**Comment by killermoehre** [comment]
I require the `--remote` option to actually update some other repository where `docsy` itself is a submodule of.

**Comment by deining** [comment]
You can overwrite the branch in your `.git/config`, the settings there take precedence over the settings given in `.gitmodules`. (either use `branch = main` or `branch = HEAD`).

```
[submodule "assets/vendor/bootstrap"]
	active = true
	url = https://github.com/twbs/bootstrap.git
	branch = HEAD
```

Be aware however, since docsy pulls in bootstrap version 4.6.1, your submodule will be out of sync.

**Comment by killermoehre** [comment]
Well, `docsy` doesn't find the `v4-dev` branch it is pointing to. I don't even want `HEAD`, I just want docsy to pull from the current `v4-dev` branch as stated in the `.gitmodule`-

**Comment by killermoehre** [comment]
The linked PR is closed. Therefore this issue can be closed.

**Comment by killermoehre** [comment]
My bad, the PR #823 is not yet merged.

**Comment by deining** [comment]
Can you please try:

```
git submodule sync
```

Does this resolve your problem?

**Comment by killermoehre** [comment]
I'm switching to proper hugo modules with
```toml
[module]
[[module.imports]]
  disable = false
  ignoreConfig = false
  ignoreImports = false
  path = 'github.com/google/docsy'
```
So, if this works, I think this issue can be closed.

**Comment by deining** [comment]
> Hmm … this doesn't work. How am I supposed to use `docsy` as a module?

Please note that using docsy as hugo module is work in progress currently it will **not** work with HEAD of docsy repo.
In order to make it work, PR #801 needs to be merged into master.

I just reworked and rebased #801, IMHO it is ready to merge and won't break anything. Once #801 were merged, you could immediately test it and report your findings back to us.

Meanwhile, you may have a look at the preliminary documentation for docsy as Hugo Module, submitted with PR #802, especially the chapter on [`Installation`](https://deploy-preview-802--docsydocs.netlify.app/docs/theme-installation/).

**Note:** In case #801 gets merged into `master` you have to enable module imports in `config.toml`, on two places, otherwise it will not work for you.

**Comment by killermoehre** [comment]
So, #801 is merged. What do I need to use `docsy` as a module?

**Comment by deining** [comment]
> So, #801 is merged. What do I need to use `docsy` as a module?

You need to convert your existing site to a Hugo module. Detailed [instructions](https://deploy-preview-802--docsydocs.netlify.app/docs/updating/convert-site-to-module/) are authored already. Good luck, please let me know if conversion worked for you!

**Comment by chalin** [comment]
I'm going to close this issue since there isn't a problem with Docsy submodules (but rather the particular nature of the context in which you are using docsy) and, in any case, you've decided to give docsy-as-a-hugo-module a try. Thanks for doing that, and as @deining says, do give us feedback either by opening another issue or a discussion.

**Comment by killermoehre** [comment]
@deining @chalin `docsy` as module works. Instructions on how to convert the site to a module are well written as well.
