### ISSUE TITLE
Possible landing page bug

### ISSUE THREAD

**Issue by sharifsalah** [google/docsy#83]
I've encountered unusual behavior on the landing page in the latest version of Docsy. It looks like `blocks/feature` under `blocks/section` are rendered as a vertical set rather than the expected horizontal layout:

<img width="1425" alt="Screen Shot 2019-06-04 at 3 32 05 PM" src="https://user-images.githubusercontent.com/6339099/58887716-05d1ad80-86de-11e9-8615-3840010d35ab.png">

Here's a summary of the steps I followed to generate the screenshot:

```bash
git clone https://github.com/google/docsy-example.git **
cd docsy-example/
git submodule update --init --recursive
git submodule update --remote
npm install
npm audit fix --force
hugo server
```

** I observe essentially the same behavior with [another repo](https://github.com/LisaFC/docsy-example-test.git).

**Comment by sharifsalah** [comment]
Related to this, it might be good to document canonical steps for testing the latest version of Docsy. If you're trying to update to the latest version of Docsy, it can be really useful to be able to test against a canonical reference point to help identify if problems are related to changes in your project vs. bugs introduced by Docsy.

Happy to create a separate issue if this sounds useful...

**Comment by LisaFC** [comment]
Ah, I think I know what's going on there. I had to tweak some of the block styling because the About page looked weird, so there are now two types of those section blocks, one for horizontally stacked ones and one for vertically stacked ones. Goldydocs is updated to use the new version but I think I *may* have done it in a way that breaks old projects. I should be able to fix it, though will also need to update the docs.

Canonical project should be Goldydocs, once we're released I'll be updating that every time we make a major change and either a)making sure it still works or b)updating and posting something about needing to make changes.

**Comment by LisaFC** [comment]
Yeah, it was this change:
https://serene-roentgen-10fbaa.netlify.com/docs/adding-content/shortcodes/#blocks-section

Does it make sense to you to leave the horizontal "feature" block as the default and have the other block type being the one you have to specify? As it means it won't break any existing sites.

**Comment by sharifsalah** [comment]
Ah yes, that makes sense, thanks. I wasn't aware of the new "feature" block.

Personally, it's no hardship for our project to migrate to specifying the "feature" block, but for the sake of other projects, I agree it makes sense to leave the behavior of the "feature" block as-is, so as not to impact any existing sites.

Let me know what you decide. If you're keeping the new behavior I can go ahead and update our project. If you're going to change the default behavior, then I'll hold off until those changes are merged.
