### ISSUE TITLE
Ensure a smooth transition for existing docsy-as-submodule users

### ISSUE THREAD

**Issue by chalin** [google/docsy#848]
To give some initial context (excerpt from https://github.com/google/docsy/discussions/535#discussioncomment-1986956):

>  - **Update of existing sites**: That's for sure the most critical part. We do have two [testimonies](https://github.com/google/docsy/issues/836#issuecomment-1014935503) that users can upgrade to HEAD of repo and use their site successfully. In it's current form, there is some manual work needed. @LisaFC @chalin Is that acceptable? Yes or no? We need to make a decision here soon.
>    That's what currently is [needed]() to make the site work again:
>    - navigate to your `themes` folder
>    - create two new directory structures (empty directories):
>     ```
>    mkdir -p github.com/twbs/bootstrap
>    mkdir -p github.com/FortAwesome/Font-Awesome
>    ```
>    No code change, simply create two empty directories and your site is up again. Is this acceptable? I don't see any **good** way to make it a seamless update without any intervention. I asked on the hugo discourse list, haven't received any answer yet. I doubt whether anyone will still come up with a good answer.
> *Disclaimer:* Yes, there actually *is* a way to make it a seamless update without any intervention. But it's not clean, and I don't like it.

**Comment by chalin** [comment]
I've actually now tried to migrate one of our sites, while seeking to continue using docsy via a submodule. As @deining mentions, the following command helps ensure that I can build locally by creating some empty directories:

```console
$ mkdir -p themes/github.com/{twbs/bootstrap,FortAwesome/Font-Awesome}
```

By default, git won't commit (and in any case will prune) empty directories. So, the above solution **breaks my remote builds** (unless I include that command as part of my build process, which I don't want to do). Thoughts @deining?

**Comment by deining** [comment]
> Thoughts @deining?

O.k. Then we have to expand our adaption routine a bit:

```
mkdir -p github.com/twbs/bootstrap
touch github.com/twbs/bootstrap/.gitkeep
mkdir -p github.com/FortAwesome/Font-Awesome
touch github.com/twbs/bootstrap/.gitkeep
```

Does this solve your problem?

**Comment by chalin** [comment]
Yes, it would likely solve the problem, but is starting to feel a little hackish. Earlier you wrote:

> there actually _is_ a way to make it a seamless update without any intervention. But it's not clean

Would you mind sharing what this seamless update path would be?

**Comment by deining** [comment]
> Yes, it would likely solve the problem, but is starting to feel a little hackish.

Yes, I agree that this is not ideal.
 
> Would you mind sharing what this seamless update path would be?

This is the idea:

Currently the project pulls in docsy which pulls in transitive dependencies `bootstrap` and `font-awesome`.

Depedendency graph is like:

```
my-site -> docsy
docsy -> bootstrap
docsy -> font-awesome
```

Dependencies are declared in `config.toml` as module, but these modules can be resolved only in module context, not in submodule context (by creating folder structure via my adaption routine, they can be resolved again).

I can make all three dependencies direct dependencies of my site:

```
my-site -> docsy
my-site -> bootstrap
my-site -> font-awesome
```

This solves the issue for submodules, and I declare the module imports inside `config.toml` of `my-site` only when I really want to use hugo modules.
But now `docsy` theme doesn't know anything about the versions of its dependencies. That's like we removed submodules `bootstrap` and `Font-Awesome` from our current repo: a no go.

What about this:

I add dependencies in `config.toml`, but comment them out. This way, there is no beaking change for submodule users any more.

```
# [module]
# [[module.imports]]
#   path = "github.com/twbs/bootstrap"
# [[module.imports.mounts]]
#   source = "scss"
#   target = "assets/vendor/bootstrap/scss"
# [[module.imports]]
#   path = "github.com/FortAwesome/Font-Awesome"
# [[module.imports.mounts]]
#   source = "scss"
#   target = "assets/vendor/Font-Awesome/scss"
```

Users that want to use docsy as hugo module make use of smudge and clean filters inside their git repo, so that the comments are removed on checkout and added again when commiting any changes. To do so, they have to add a file `.gitattributes` at the root level of their checkout:

```
# setting smudge and clean filter
config.toml filter=RemoveModuleComments
```

Afterwards, they have to declare the used filter inside their `gitconfig`:

```
[core]
	autocrlf = false
[filter "RemoveModuleComments"]
  smudge = sed 29-50s/^#//   # untested, just to get the idea
```

Isn't that a much better approach? WDYT?

**Comment by chalin** [comment]
Firstly, I'd suggest that we leave dependencies the way they are (that is, not suggest that projects pull up docsy subdependencies to the top level).

As you might know, Hugo supports multiple config files as well as config directories -- for details, see [Configure Hugo](https://gohugo.io/getting-started/configuration/). That, in my opinion, might offer a better solution. I'd move the `module` config entries into, say, `module.toml`. Then we'll need to figure out how projects, that are importing docsy as a module, can reference the proper config. @deining can you explore that possibility? (If not, I'll give it a try as soon as I can.)

**Comment by deining** [comment]
> As you might know, Hugo supports multiple config files as well as config directories

I know. I myself [proposed](https://github.com/google/docsy/pull/491#issue-840685784) to use them inside the docsy theme, this proposal was declined.

> That, in my opinion, might offer a better solution.

It certainly is.

**config directories**:

Yes, I thought of this already. As stated in this [forum thread](https://discourse.gohugo.io/t/hugo-theme-module-with-nested-module/28199/6), this doesn't work, however:

```
We should double check that the documentation
is clear about this (and we should probably warn
about it if we can detect it), but the config directory
is only read for the main project.
Themes/theme modules is config.toml etc. only.
```

**Multiple config files**. I haven't thought of this, this is a great idea, thanks a lot! That sounds really appealing and I will give it a try as soon as I can.

**Comment by deining** [comment]
> So #850 will not work with previous hugo versions, we have to determine as of which version hugo learned to handle `config` directories inside themes properly. According to our findings, we may have to increase the minimum hugo version required when using docsy theme.

I found it out meanwhile: As of version [0.84](https://gohugo.io/news/0.84.0-relnotes/#themes-now-support-the-config-directory) the use of the `config` directory inside themes is supported. This is the minimum version when using docsy theme as hugo module. Using docsy as submodule might work with earlier versions, too, which is good since the majority of sites will still run docsy as submodule.

**Comment by chalin** [comment]
@deining - I find interesting the solution you've proposed in https://github.com/google/docsy/pull/852#issuecomment-1018307394. Here are my thoughts ...

Given that the use of docsy as a Hugo module hasn't been fully vetted nor (in my opinion) sufficiently field tested, I believe that it is premature to force users (by breaking their builds) to choose between a solution that they're already content in using (submodules) vs. a new not-fully-vetted approach.

I'd like to propose the following, which I'll frame in terms of releases:

### Next release (v0.2.0)

The next release of Docsy (v0.2.0), should be usable by current users _without_ any changes to their build, while introducing opt-in use of Docsy as a Hugo module, possibly using the approach you've already worked out in https://github.com/google/docsy/pull/852#issuecomment-1018307394:

```console
$ hugo serve --configDir docsy-module
```

We need to give users the time to try this approach, and get feedback from them. For example, we don't know how this will actually play out for projects that, for example, already have other configDir(s) and/or a mix of custom config files.

**Note:** given that the configDir name seems to have a "global" scope, it would probably be better to choose a docsy-specific names like `docsy-module` and `docsy-submodule` rather than `configModule` and  `configTheme`.

### Later release (v0.3.0+)

Once we've collected enough feedback from users, and have had some field experience ourselves, we'll be in a better position to settle on a solution that works for all.

Eventually, if we so decide, we could switch the default way in which docsy is used or, as you proposed in https://github.com/google/docsy/pull/852#issuecomment-1018307394 force users to make an enlightened decision.

Thoughts? @deining @LisaFC @emckean

**Comment by huehnerlady** [comment]
@chalin to me as a user of docsy that sounds like a good option. I use dependabot for the docsy theme as a submodule and currently all the updates of the theme are red as so far I could not find a good solution in how to make the current master work. my thought about that is to disable the update from dependabot for now and at some point update docsy again manually.

I would be super happy if the master would be cleaned up for us to be able to upgrade. I would also be happy to try the new module way, but more as a 'can'do instead of a 'must', especially as there are some hacks involved which I am usually not happy with using in production...

**Comment by h1z3y3** [comment]
@huehnerlady  +1 
I'm waiting for the official document about using docsy in module.

**Comment by deining** [comment]
> **Note:** given that the configDir name seems to have a "global" scope, it would probably be better to choose a docsy-specific names like `docsy-hugo-module` and `docsy-git-submodule` rather than `configModule` and `configTheme`.

I see the point, but I'm not fully convinced yet, since this renaming removes the notion that this a a `config` dir.

What about `config-docsy-hugo-module` and `config-docsy-git-submodule`? That's more precise, but having to type `hugo serve --configDir config-docsy-git-submodule` is a kind of a hassle. I chose short directory names for a reason!

Feedback/opinions are appreciated here!

**Comment by deining** [comment]
I took a bit longer than expected, but now we have #871 in place which ensures a smooth transition for users that use docsy traditionally (as git submodule).
